services:
  app:
    build: .
    container_name: library-management-system-be
    ports:
      - '3001:3001'
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    restart: unless-stopped

  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: mysql
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  mysqldata:
  redisdata:
